version: 0.3

phases:
  install:
    commands:
      - echo Installing dependencies...

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Optional if you want to push to ECR
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <your_account_id>.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - docker build -t cpp-app .

  post_build:
    commands:
      - echo Running tests...
      - docker run cpp-app ./build/my_app --run-tests
      - echo Build and tests completed.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
