version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...
      - apt-get update && apt-get install -y docker.io

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # Optional: if you plan to push to ECR
      # - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

  build:
    commands:
      - echo Building Docker image...
      - docker build -t cpp-app .

  post_build:
    commands:
      - echo Running tests...
      - docker run cpp-app ./build/my_app --run-tests
      # Replace --run-tests with your test flag or command
      - echo Build and tests completed.

artifacts:
  files:
    - '**/*'
  discard-paths: yes
